name: CD

on:
  workflow_dispatch: {}
  schedule:
    - cron: "0 6 * * 1"

jobs:
  deploy-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install Ansible
        run: pip install ansible

      - name: Create vault password file
        run: echo "${{ secrets.VAULT_PASSWORD }}" > .vault_pass.txt

      - name: Generate .env from Vault
        run: |
          ansible-playbook deploy.yml --vault-password-file .vault_pass.txt --tags "env_only"

      - name: Validate required env vars
        run: |
          source .env
          if [ -z "$QDRANT_API_KEY" ]; then exit 1; fi
          if [ -z "$DOCKERHUB_USERNAME" ]; then exit 1; fi
          if [ -z "$KAFKA_BOOTSTRAP_SERVERS" ]; then echo "missing kafka"; exit 1; fi
          if [ -z "$KAFKA_USERNAME" ]; then echo "missing kafka user"; exit 1; fi
          if [ -z "$KAFKA_PASSWORD" ]; then echo "missing kafka pass"; exit 1; fi
          if [ -z "$KAFKA_CLUSTER_ID" ]; then echo "missing kafka cluster id"; exit 1; fi

      - name: Login to DockerHub
        run: |
          source .env
          echo $DOCKERHUB_TOKEN | docker login -u $DOCKERHUB_USERNAME --password-stdin

      - name: Pull image
        run: |
          source .env
          IMAGE="$DOCKERHUB_USERNAME/bd-lab-4:latest"
          docker pull "$IMAGE"

      - name: Start Qdrant
        run: |
          source .env
          docker network create app-net || true

          docker run -d \
            --network app-net \
            -p $QDRANT_PORT:$QDRANT_PORT \
            -e QDRANT__SERVICE__API_KEY=$QDRANT_API_KEY \
            -e KAFKA_BOOTSTRAP_SERVERS=$KAFKA_BOOTSTRAP_SERVERS \
            -e KAFKA_SECURITY_PROTOCOL=$KAFKA_SECURITY_PROTOCOL \
            -e KAFKA_SASL_MECHANISM=$KAFKA_SASL_MECHANISM \
            -e KAFKA_USERNAME=$KAFKA_USERNAME \
            -e KAFKA_PASSWORD=$KAFKA_PASSWORD \
            --name qdrant \
            qdrant/qdrant

      - name: Wait for Qdrant
        run: |
          source .env
          for i in {1..30}; do
            if curl -sf \
              -H "api-key: $QDRANT_API_KEY" \
              http://localhost:6333 > /dev/null; then
              exit 0
            fi
            sleep 2
          done
          docker logs qdrant
          exit 1

      - name: Start Kafka (KRaft)
        run: |
          source .env
          docker network create app-net || true

          docker run -d \
            --network app-net \
            -p 9092:9092 \
            --name kafka \
            -e KAFKA_PROCESS_ROLES=broker,controller \
            -e KAFKA_NODE_ID=1 \
            -e KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093 \
            -e KAFKA_LISTENERS=SASL_PLAINTEXT://0.0.0.0:9092,CONTROLLER://0.0.0.0:9093 \
            -e KAFKA_ADVERTISED_LISTENERS=SASL_PLAINTEXT://kafka:9092 \
            -e KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=SASL_PLAINTEXT:SASL_PLAINTEXT,CONTROLLER:PLAINTEXT \
            -e KAFKA_INTER_BROKER_LISTENER_NAME=SASL_PLAINTEXT \
            -e KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER \
            -e KAFKA_SASL_ENABLED_MECHANISMS=PLAIN \
            -e KAFKA_SASL_MECHANISM_INTER_BROKER_PROTOCOL=PLAIN \
            -e KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1 \
            -e CLUSTER_ID=$KAFKA_CLUSTER_ID \
            -e KAFKA_OPTS=-Djava.security.auth.login.config=/etc/kafka/jaas.conf \
            confluentinc/cp-kafka:latest \
            bash -c '
              echo "KafkaServer {
                org.apache.kafka.common.security.plain.PlainLoginModule required
                username=\"admin\"
                password=\"admin-secret\"
                user_admin=\"admin-secret\";
              };" > /etc/kafka/jaas.conf &&
            
              echo "security.protocol=SASL_PLAINTEXT
            sasl.mechanism=PLAIN
            sasl.jaas.config=org.apache.kafka.common.security.plain.PlainLoginModule required username=\"admin\" password=\"admin-secret\";" > /etc/kafka/client.properties &&
            
              /etc/confluent/docker/run &
            
              echo "Waiting for Kafka..." &&
              sleep 15 &&
            
              kafka-topics \
                --bootstrap-server localhost:9092 \
                --command-config /etc/kafka/client.properties \
                --create \
                --if-not-exists \
                --topic predictions \
                --partitions 3 \
                --replication-factor 1 &&
            
              wait
            '

      - name: Wait for Kafka
        run: |
          for i in {1..30}; do
            nc -z localhost 9092 && echo "Kafka is ready" && exit 0
            echo "Waiting for Kafka..."
            sleep 3
          done
          docker logs kafka
          exit 1

      - name: Run API container
        run: |
          source .env
          IMAGE="$DOCKERHUB_USERNAME/bd-lab-4:latest"

          docker run -d \
            --network app-net \
            --name fashion_api \
            -p 8000:8000 \
            -e QDRANT_HOST=$QDRANT_HOST \
            -e QDRANT_PORT=$QDRANT_PORT \
            -e QDRANT_API_KEY=$QDRANT_API_KEY \
            -e DAGSHUB_ACCESS_KEY=$DAGSHUB_ACCESS_KEY \
            -e DAGSHUB_SECRET_KEY=$DAGSHUB_SECRET_KEY \
            "$IMAGE"

      - name: Wait for API ready
        run: |
          for i in {1..30}; do
            if curl -s http://localhost:8000/health | grep -q "ok"; then
              exit 0
            fi
            sleep 2
          done
          docker logs fashion_api
          exit 1

      - name: Install httpx
        run: pip install httpx

      - name: Run functional scenario
        run: python tools/run_scenario.py scenario.json

      - name: Cleanup
        if: always()
        run: |
          docker stop fashion_api || true